#!/usr/bin/env bash
# setup-prod.sh — Bootstrap /etc/prakombot/notifier.env on the VPS
#
# What it does:
#   1. Generates a fresh WEBHOOK_SECRET (64 hex chars)
#   2. Prompts for (or accepts via flags) TELEGRAM_BOT_TOKEN, CHAT_ID, THREAD_ID
#   3. Validates each input against expected format
#   4. Writes /etc/prakombot/notifier.env (mode 0600, owned by root:notifier)
#   5. Backs up any existing env file to /etc/prakombot/notifier.env.bak.<ts>
#   6. Prints the new WEBHOOK_SECRET so you can paste it into GAS Script Properties
#   7. Shows the resulting file content (with secret redacted)
#
# Usage:
#   sudo ./setup-prod.sh                          # interactive prompts
#   sudo ./setup-prod.sh --dry-run                # show what would happen, no writes
#   sudo ./setup-prod.sh --bot-token "123:ABC" --chat-id "-1001" --thread-id 25
#   sudo ./setup-prod.sh --webhook-host 0.0.0.0   # change bind address
#
# Run as root (or with sudo) — needs to write /etc/prakombot/.

set -euo pipefail

ENV_DIR="/etc/prakombot"
ENV_FILE="${ENV_DIR}/notifier.env"
SERVICE_USER="notifier"

DRY_RUN=false
BOT_TOKEN=""
CHAT_ID=""
THREAD_ID=""
WEBHOOK_HOST="127.0.0.1"
WEBHOOK_PORT="8000"
PARSE_MODE="HTML"
MAX_RETRIES="3"
RETRY_BASE="1"

# --- arg parsing -----------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run) DRY_RUN=true; shift ;;
        --bot-token) BOT_TOKEN="$2"; shift 2 ;;
        --chat-id) CHAT_ID="$2"; shift 2 ;;
        --thread-id) THREAD_ID="$2"; shift 2 ;;
        --webhook-host) WEBHOOK_HOST="$2"; shift 2 ;;
        --webhook-port) WEBHOOK_PORT="$2"; shift 2 ;;
        --parse-mode) PARSE_MODE="$2"; shift 2 ;;
        --max-retries) MAX_RETRIES="$2"; shift 2 ;;
        --retry-base) RETRY_BASE="$2"; shift 2 ;;
        -h|--help)
            grep '^#' "$0" | sed 's/^# \?//'
            exit 0 ;;
        *)
            echo "Unknown arg: $1" >&2
            exit 2 ;;
    esac
done

# --- preflight -------------------------------------------------------------
if [[ $EUID -ne 0 ]] && ! $DRY_RUN; then
    echo "ERROR: must run as root (or with sudo) — needs to write ${ENV_FILE}" >&2
    exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
    echo "ERROR: openssl not found — required to generate WEBHOOK_SECRET" >&2
    exit 1
fi

# --- interactive prompts (only if a value is missing) ----------------------
prompt() {
    local var_name="$1"
    local prompt_text="$2"
    local validator="$3"
    local current="${!var_name:-}"
    if [[ -n "$current" ]]; then
        if $validator "$current" 2>/dev/null; then
            return 0
        else
            echo "Provided $var_name failed validation, re-prompting." >&2
        fi
    fi
    while true; do
        read -r -p "$prompt_text" current
        if validator "$current" 2>/dev/null; then
            eval "$var_name=\$current"
            return 0
        fi
        echo "  invalid — try again." >&2
    done
}

validate_bot_token() {
    [[ "$1" =~ ^[0-9]+:[A-Za-z0-9_-]+$ ]] && [[ ${#1} -ge 30 ]]
}
validate_chat_id() {
    [[ "$1" =~ ^-[0-9]+$ ]]
}
validate_thread_id() {
    [[ "$1" =~ ^[0-9]+$ ]]
}

if ! $DRY_RUN; then
    echo "=== Notifier production setup ==="
    echo
    prompt BOT_TOKEN  "Telegram bot token (from BotFather, format 123456:ABC-DEF...): " validate_bot_token
    prompt CHAT_ID    "Telegram chat ID (negative, e.g. -1001234567890):             " validate_chat_id
    prompt THREAD_ID  "Forum topic message_thread_id (integer, 0 if no topic):         " validate_thread_id
    echo
fi

# --- generate webhook secret ------------------------------------------------
WEBHOOK_SECRET=$(openssl rand -hex 32)
[[ ${#WEBHOOK_SECRET} -eq 64 ]] || { echo "FATAL: openssl produced wrong-length secret" >&2; exit 1; }

# --- compose env file -------------------------------------------------------
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
ENV_CONTENT=$(cat <<EOF
# notifier.env — generated by setup-prod.sh at ${TIMESTAMP}
# DO NOT COMMIT. Mode 0600. Owner root:${SERVICE_USER}.

TELEGRAM_BOT_TOKEN=${BOT_TOKEN}
TELEGRAM_CHAT_ID=${CHAT_ID}
TELEGRAM_THREAD_ID=${THREAD_ID}
TELEGRAM_PARSE_MODE=${PARSE_MODE}
TELEGRAM_MAX_RETRIES=${MAX_RETRIES}
TELEGRAM_RETRY_BASE_SECONDS=${RETRY_BASE}

WEBHOOK_SECRET=${WEBHOOK_SECRET}
WEBHOOK_HOST=${WEBHOOK_HOST}
WEBHOOK_PORT=${WEBHOOK_PORT}
EOF
)

# --- preview / write --------------------------------------------------------
echo "=== Preview ==="
echo "$ENV_CONTENT" | sed "s|^WEBHOOK_SECRET=.*|WEBHOOK_SECRET=<64 hex chars, will be shown below>|"
echo
echo "WEBHOOK_SECRET (you MUST copy this into GAS Script Properties WEBHOOK_SECRET):"
echo "  ${WEBHOOK_SECRET}"
echo

if $DRY_RUN; then
    echo "=== DRY RUN — no files written ==="
    exit 0
fi

# --- ensure notifier user exists -------------------------------------------
if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
    echo "Creating system user '${SERVICE_USER}'..."
    useradd --system --shell /usr/sbin/nologin --home-dir /opt/prakombot "$SERVICE_USER"
fi

# --- ensure env dir exists --------------------------------------------------
mkdir -p "$ENV_DIR"
chown root:"$SERVICE_USER" "$ENV_DIR"
chmod 0750 "$ENV_DIR"

# --- backup existing file --------------------------------------------------
if [[ -f "$ENV_FILE" ]]; then
    BACKUP="${ENV_FILE}.bak.$(date +%Y%m%d-%H%M%S)"
    echo "Backing up existing ${ENV_FILE} -> ${BACKUP}"
    cp -p "$ENV_FILE" "$BACKUP"
    chown root:"$SERVICE_USER" "$BACKUP"
    chmod 0600 "$BACKUP"
fi

# --- write new file --------------------------------------------------------
echo "$ENV_CONTENT" > "$ENV_FILE"
chown root:"$SERVICE_USER" "$ENV_FILE"
chmod 0640 "$ENV_FILE"

# --- summary ---------------------------------------------------------------
echo "=== Done ==="
echo "Wrote ${ENV_FILE} (mode 0640, owner root:${SERVICE_USER})"
echo
echo "=== Next steps ==="
echo "1. Copy WEBHOOK_SECRET above into GAS Script Properties (Project Settings -> Script Properties):"
echo "     key=WEBHOOK_SECRET  value=<the secret above>"
echo "2. Set WEBHOOK_URL in GAS Script Properties:"
echo "     key=WEBHOOK_URL  value=https://pb.kotakpasir.my.id/webhook/form"
echo "3. Reload systemd + start service:"
echo "     sudo systemctl daemon-reload"
echo "     sudo systemctl enable --now form-bot"
echo "     sudo systemctl status form-bot"
echo "4. Smoke test:"
echo "     curl -fsS https://pb.kotakpasir.my.id/healthz"
echo
echo "5. Rotate backup: keep ${BACKUP:-N/A} (no rotation needed if you trust the new file)"
